### ISSUE TITLE
issue loading the plugin

### ISSUE THREAD

**Issue by costasfait** [lymperis-e/Greek-Data-QGIS-Plugin#3]
I get the following error when I load the plug in with QGIS 3.16.14 - there seems no problem with previous versions.

![image](https://user-images.githubusercontent.com/65224259/146540538-ed7e35b3-f51e-4887-b3ca-ee72aee5f011.png)

**Comment by lymperis-e** [comment]
Costas, I am sorry for the late reply. I have uploaded a new version (1.0.7) and soon another one will follow. The error seems to be a wrong gist path(*see below), which is fixed in v 1.0.7. Try installing it, and the error should go away. Thank you for your feedback, I should hopefully have more time to go over my github account from now and, and will thus be responding in reasonable time. 

*: The plugin reads the data sources from a remote gist url that contains a json string. At some point I uploaded a version with a wrong gist url, which is probably what you happened to doanload.
